allowBuilds:
  bufferutil: false
  protobufjs: true
  unrs-resolver: true
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@4.0.108'
  - '@ai-sdk/provider-utils@5.0.57'
  - '@ai-sdk/provider@4.0.25'
  - ai@7.0.133
  - '@ai-sdk/google@4.0.92'
  - '@ai-sdk/mcp@2.0.71'
  - '@ai-sdk/react@4.0.136'
onlyBuiltDependencies:
  - unrs-resolver
overrides:
  source-map-js: 1.2.2
  sharp: 0.35.5
  '@grpc/grpc-js': 1.14.5
  undici@6: 6.28.1
  '@circle-fin/w3s-pw-web-sdk>uuid': 11.1.1
  toml: 4.2.0
  jayson>uuid: 11.1.1
  jayson>stream-json: 3.7.0
