"use client";

import { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { ArrowRight, LockKeyhole, X } from "lucide-react";
import { MoneyValue, SectionCard, SectionHeading, StatusPill } from "./primitives";
import { useTreasuryWorkspace } from "./treasury-workspace-provider";
import { formatPercentFromBps } from "@/lib/treasury/format";
import type { StrategyKind } from "@/lib/treasury/models";

const labels: Record<StrategyKind, string> = { LIQUID: "Liquid USDC", MORPHO: "Morpho", USYC: "USYC", BTC_RESERVE: "BTC Reserve" };
const inputClass = "mt-2 w-full border border-black/20 bg-white px-3 py-2.5 text-sm outline-none focus:border-[#164b32]";

export function InvestmentWorkspace() {
  const { workspace, assessment, allocationPlan, updateTargets, storageIssue } = useTreasuryWorkspace();
  const [targets, setTargets] = useState<Record<StrategyKind, string>>(Object.fromEntries(Object.entries(workspace.targetAllocationsBps).map(([key, value]) => [key, String(value / 100)])) as Record<StrategyKind, string>);
  const [error, setError] = useState("");
  const saveTargets = (event: React.FormEvent) => {
    event.preventDefault(); setError("");
    const values = Object.fromEntries(Object.entries(targets).map(([key, value]) => [key, Number(value)])) as Record<StrategyKind, number>;
    if (Object.values(values).some((value) => !Number.isFinite(value) || value < 0 || value > 100)) return setError("Each target must be between 0 and 100");
    if (Object.values(values).reduce((sum, value) => sum + value, 0) !== 100) return setError("Target allocations must total exactly 100%");
    updateTargets(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Math.round(value * 100)])) as Record<StrategyKind, number>);
  };
  return <div className="metric-grid mx-auto max-w-[1440px] px-5 py-7 md:px-8 lg:px-10 lg:py-10"><div className="grid gap-6 lg:grid-cols-[1fr_340px]">
    <div className="space-y-6"><SectionCard><SectionHeading index="02.1" title="Strategy shelf" description="Availability is explicit; no protocol adapter is connected" /><div className="grid sm:grid-cols-2">{workspace.strategies.map((strategy) => <article key={strategy.id} className="flex min-h-52 flex-col border-b border-black/15 p-5 odd:sm:border-r"><div className="flex items-start justify-between gap-3"><div><p className="mono text-[9px] uppercase text-black/40">{labels[strategy.kind]}</p><h2 className="mt-2 text-lg font-medium">{strategy.name}</h2></div><StatusPill label={workspace.policy.enabledStrategies[strategy.kind] ? "Preview enabled" : strategy.integration} tone={workspace.policy.enabledStrategies[strategy.kind] ? "success" : "neutral"} /></div><div className="mt-auto grid grid-cols-3 gap-3 border-t border-black/10 pt-4"><div><p className="text-[9px] uppercase text-black/35">APY</p><p className="mono mt-1 text-xs">{strategy.apyBps === null ? "—" : formatPercentFromBps(strategy.apyBps, 2)}</p></div><div><p className="text-[9px] uppercase text-black/35">Risk</p><p className="mono mt-1 text-xs">{strategy.risk}</p></div><div><p className="text-[9px] uppercase text-black/35">Cap</p><p className="mono mt-1 text-xs">{formatPercentFromBps(workspace.policy.strategyCapsBps[strategy.kind])}</p></div></div></article>)}</div></SectionCard>
      <SectionCard><SectionHeading index="02.2" title="Target allocation" description="Targets apply only to deployable capital" /><form onSubmit={saveTargets} className="p-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{(Object.keys(labels) as StrategyKind[]).map((kind) => <label key={kind} className="text-[10px] font-semibold uppercase tracking-[0.1em] text-black/50">{labels[kind]} %<input aria-label={`${labels[kind]} target`} value={targets[kind]} onChange={(event) => setTargets((current) => ({ ...current, [kind]: event.target.value }))} inputMode="decimal" className={inputClass} /></label>)}</div>{error && <p role="alert" className="mt-4 border border-[#9a433c]/20 bg-[#f5dedb] p-3 text-xs text-[#7b332d]">{error}</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-4"><p className="text-xs text-black/45">Disabled or capped allocations remain Liquid USDC; they are never reassigned to a riskier strategy.</p><button disabled={Boolean(storageIssue)} className="border border-black/20 px-4 py-3 text-xs font-semibold hover:bg-black/5 disabled:opacity-40">Save targets</button></div></form></SectionCard>
    </div>
    <aside className="space-y-6"><SectionCard><SectionHeading index="02.3" title="Capital boundary" /><div className="space-y-4 p-5"><div><p className="text-[10px] uppercase text-black/40">Treasury</p><MoneyValue money={workspace.totalTreasury} className="mt-1 block text-xl" /></div><div className="border-t border-black/10 pt-4"><p className="text-[10px] uppercase text-black/40">Protected</p><MoneyValue money={assessment.protectedCapital} className="mt-1 block text-xl" /></div><div className="border-t border-black/10 pt-4"><p className="text-[10px] uppercase text-[#164b32]">Deployable</p><MoneyValue money={assessment.deployableCapital} className="mt-1 block text-xl text-[#164b32]" /></div></div></SectionCard>
      <Dialog.Root><Dialog.Trigger asChild><button className="flex w-full items-center justify-between bg-[#0b0d0c] px-5 py-4 text-sm font-semibold text-white hover:bg-[#242824]">Preview engine plan <ArrowRight className="size-4" /></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/60" /><Dialog.Content aria-describedby="investment-preview-description" className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto bg-[#fffdf7] shadow-2xl focus:outline-none"><div className="sticky top-0 flex items-center justify-between border-b border-black/15 bg-[#fffdf7] px-5 py-4"><div><p className="mono text-[9px] uppercase text-black/40">Deterministic preview</p><Dialog.Title className="mt-1 text-lg font-semibold">Allocation plan</Dialog.Title></div><Dialog.Close aria-label="Close investment preview" className="grid size-10 place-items-center border border-black/15"><X className="size-4" /></Dialog.Close></div><Dialog.Description id="investment-preview-description" className="px-5 pt-5 text-sm leading-6 text-black/55">Calculated from deployable capital, strategy availability and policy caps. No proposal or transaction is created.</Dialog.Description><div className="m-5 border border-black/15"><div className="border-b border-black/15 bg-black/[0.03] p-4"><div className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="size-4" />Protected capital</div><MoneyValue money={assessment.protectedCapital} className="mt-2 block text-2xl" /></div>{allocationPlan.lines.map((line) => <div key={line.strategy} className="border-b border-black/10 p-4"><div className="flex items-center justify-between gap-4"><p className="text-sm font-semibold">{labels[line.strategy]}</p><MoneyValue money={line.approved} className="text-xs" /></div><p className="mt-1 text-xs text-black/45">Requested <MoneyValue money={line.requested} /> · {line.reason}</p></div>)}<div className="p-4"><div className="flex items-center justify-between"><p className="text-sm font-semibold">Liquid remainder</p><MoneyValue money={allocationPlan.unallocatedToLiquid} className="text-xs" /></div></div></div><div className="mx-5"><StatusPill label={allocationPlan.status} tone={allocationPlan.status === "PASS" ? "success" : "warning"} /><p className="mt-3 text-xs leading-5 text-black/50">{allocationPlan.violations.map((item) => item.message).join(" ") || "All requested allocations fit the current policy."}</p></div><div className="p-5"><button disabled className="w-full cursor-not-allowed border border-black/15 bg-black/5 px-5 py-4 text-sm font-semibold text-black/35">Execution begins in a later stage</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
    </aside>
  </div></div>;
}
