import { treasuryFixtureSchema } from "./models";

const usdc = (minorUnits: string) => ({ currency: "USDC" as const, minorUnits, decimals: 6 });

export const demoTreasury = treasuryFixtureSchema.parse({
  portfolio: {
    updatedAt: "2026-09-27T09:30:00.000Z",
    totalTreasury: usdc("10000000000"),
    liquidUsdc: usdc("10000000000"),
    upcomingObligations: usdc("4500000000"),
    safetyBuffer: usdc("1000000000"),
    deployableCapital: usdc("4500000000"),
    pendingTransactions: usdc("0"),
    liquidityCoverageBps: 22222,
    nextPaymentId: "obl-payroll-oct",
    nextPaymentStatus: "SAFE",
    allocations: [
      { strategyId: "liquid-usdc", label: "Liquid USDC", percentageBps: 10000, tone: "mint" },
    ],
  },
  obligations: [
    {
      id: "obl-payroll-oct",
      title: "October payroll",
      category: "PAYROLL",
      amount: usdc("4000000000"),
      dueAt: "2026-10-04T17:00:00.000Z",
      recipient: "Payroll batch · 8 recipients",
      priority: "CRITICAL",
      status: "UPCOMING",
      description: "Monthly payroll reserve for the core team. This record is sample data and cannot be paid in Stage 1.",
    },
    {
      id: "obl-aws-oct",
      title: "AWS infrastructure",
      category: "SUBSCRIPTION",
      amount: usdc("500000000"),
      dueAt: "2026-10-08T17:00:00.000Z",
      recipient: "Vendor address not connected",
      priority: "HIGH",
      status: "UPCOMING",
      description: "Estimated monthly cloud bill. Recipient verification is deferred to a later stage.",
    },
    {
      id: "obl-invoice-104",
      title: "Invoice #104",
      category: "VENDOR",
      amount: usdc("2000000000"),
      dueAt: "2026-10-12T17:00:00.000Z",
      recipient: "0x••••••••A104 · unverified demo",
      priority: "NORMAL",
      status: "DRAFT",
      description: "Draft vendor invoice. Draft obligations are not included in the displayed protected amount.",
    },
  ],
  strategies: [
    {
      id: "liquid-usdc",
      name: "Liquid USDC",
      kind: "LIQUID",
      balance: usdc("10000000000"),
      apyBps: null,
      risk: "LOW",
      liquidity: "INSTANT",
      integration: "DEMO",
    },
    {
      id: "morpho-usdc",
      name: "Morpho USDC Vault",
      kind: "MORPHO",
      balance: usdc("0"),
      apyBps: 412,
      risk: "MODERATE",
      liquidity: "VARIABLE",
      integration: "DEMO",
    },
    {
      id: "usyc-reserve",
      name: "USYC Reserve",
      kind: "USYC",
      balance: usdc("0"),
      apyBps: null,
      risk: "LOW",
      liquidity: "RESTRICTED",
      integration: "UNAVAILABLE",
    },
    {
      id: "btc-reserve",
      name: "BTC Reserve",
      kind: "BTC_RESERVE",
      balance: usdc("0"),
      apyBps: null,
      risk: "HIGH",
      liquidity: "VARIABLE",
      integration: "FUTURE",
    },
  ],
  activities: [
    {
      id: "act-1",
      occurredAt: "2026-09-27T09:30:00.000Z",
      actor: "AGENT",
      action: "Allocation recommendation prepared",
      summary: "Keep 5,500 USDC protected and make up to 4,500 USDC available for review.",
      reason: "The demo treasury includes 4,500 USDC of upcoming obligations and a 1,000 USDC safety buffer.",
      policy: { status: "PASS", label: "Liquidity floor", reason: "Protected liquidity remains represented in the sample plan." },
      approval: "PENDING",
      execution: "DEMO_ONLY",
    },
    {
      id: "act-2",
      occurredAt: "2026-09-27T09:14:00.000Z",
      actor: "HUMAN",
      action: "Safety buffer recorded",
      summary: "Demo safety buffer set to 1,000 USDC.",
      reason: "User-authored treasury preference in the sample scenario.",
      policy: { status: "NOT_EVALUATED", label: "Stage 1 fixture", reason: "Policy Engine is not implemented." },
      approval: "NOT_REQUIRED",
      execution: "DEMO_ONLY",
    },
    {
      id: "act-3",
      occurredAt: "2026-09-27T09:00:00.000Z",
      actor: "SYSTEM",
      action: "Demo workspace initialized",
      summary: "Three sample obligations and four strategy states loaded.",
      reason: "Stage 1 uses read-only fixture data to demonstrate the product flow.",
      policy: { status: "NOT_EVALUATED", label: "No live policy", reason: "No calculation or execution occurred." },
      approval: "NOT_REQUIRED",
      execution: "DEMO_ONLY",
    },
  ],
  decisions: [
    {
      id: "decision-1",
      createdAt: "2026-09-27T09:30:00.000Z",
      title: "Preserve the payment runway",
      summary: "Keep obligations and the safety buffer liquid before reviewing any investment.",
      rationale: "Payment readiness has priority over yield. The recommendation is explanatory only in Stage 1.",
      policy: { status: "PASS", label: "Sample liquidity check", reason: "Fixture values retain 5,500 USDC as protected liquidity." },
    },
    {
      id: "decision-2",
      createdAt: "2026-09-27T09:28:00.000Z",
      title: "Do not route to unavailable strategies",
      summary: "USYC and BTC Reserve remain outside the actionable demo preview.",
      rationale: "Eligibility, market data and execution adapters are not connected.",
      policy: { status: "BLOCKED", label: "Integration boundary", reason: "Unavailable integrations cannot receive allocations." },
    },
  ],
  integrations: [
    { name: "Circle Wallet", status: "NOT_CONNECTED", message: "Planned for Stage 3. No credentials or wallet session are present." },
    { name: "Arc Testnet", status: "NOT_CONNECTED", message: "The UI is demo-only and makes no RPC requests." },
    { name: "Morpho", status: "UNAVAILABLE", message: "Vault discovery and execution are planned for Stage 4." },
  ],
});
